#include QMK_KEYBOARD_H

#define CK_LPRT LSFT(KC_9)              // Left Parentheses 
#define CK_RPRT LSFT(KC_0)              // Right Parentheses
#define CK_LCBR LSFT(KC_LBRC)           // Left Curly Brace 
#define CK_RCBR LSFT(KC_RBRC)           // Right Curly Brace

#define CK_LASLCT LALT(LSFT(KC_LEFT))   // Move and select to start of word
#define CK_RASLCT LALT(LSFT(KC_RGHT))   // Move and select to end of word

#define CK_LAMV LALT(KC_LEFT)           // Move to start of word
#define CK_RAMV LALT(KC_RGHT)           // Move to end of word
#define CK_LBMV LGUI(KC_LEFT)           // Move to start of line
#define CK_RBMV LGUI(KC_RGHT)           // Move to end of line

#define CK_SWAPP LGUI(KC_TAB)           // Switch app
#define CK_SWWNW LGUI(KC_ZKHK)          // Switch window 

#define CK_SMBS LALT(KC_BSPC)           // Delete to start of word
#define CK_BGBS LGUI(KC_BSPC)           // Delete line
#define CK_SMDL LALT(KC_DEL)            // Delete to end of word

#define CK_UNDO LGUI(KC_Z)              // Redo
#define CK_REDO LGUI(KC_Y)              // Undo

// IntelliJ Utils
#define IJ_RFCTR LSFT(KC_F6)            // Rename

// Tabs
#define CK_LTAB LALT(LSFT(KC_LBRC))     // Next tab
#define CK_RTAB LALT(LSFT(KC_RBRC))     // Previous tab

// Screen Capture
#define CK_CAPW LGUI(LSFT(KC_3))        // Capture whole screen
#define CK_CPYW LGUI(LSFT(LCTL(KC_3)))  // Copy whole screen
#define CK_CAPP LGUI(LSFT(KC_4))        // Capture portion of screen
#define CK_CPYP LGUI(LSFT(LCTL(KC_4)))  // Copy portion of screen
#define CK_CPRC LGUI(LSFT(KC_5))        // Record screen


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  [0] = LAYOUT_default(
    KC_Q,  KC_W,  KC_E,    KC_R,  KC_T,          KC_Y,          KC_U,  KC_I,    KC_O,    KC_P,
    KC_A,  KC_S,  KC_D,    KC_F,  KC_G,          KC_H,          KC_J,  KC_K,    KC_L,    KC_SCLN,
    KC_Z,  KC_X,  KC_C,    KC_V,  KC_B,          KC_N,          KC_M,  KC_COMM, KC_DOT,  KC_SLSH, MO(5),
    MO(6), MO(7), KC_LGUI, MO(1), LT(8, KC_ENT), LT(9, KC_SPC), MO(2), KC_LSFT, XXXXXXX, KC_RCTL, MO(4)
  ),

  [1] = LAYOUT_default(
    KC_ESC,  CK_SMBS, KC_UP,   CK_BGBS, XXXXXXX, XXXXXXX, KC_1,    KC_2, KC_3,    KC_DEL,
    KC_ZKHK, KC_LEFT, KC_DOWN, KC_RGHT, XXXXXXX, XXXXXXX, KC_4,    KC_5, KC_6,    KC_BSPC,
    KC_LCTL, CK_REDO, XXXXXXX, KC_LGUI, XXXXXXX, XXXXXXX, KC_7,    KC_8, KC_9,    XXXXXXX, XXXXXXX,
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, KC_LSFT, KC_0, XXXXXXX, XXXXXXX, XXXXXXX
  ),

  [2] = LAYOUT_default(
    XXXXXXX, XXXXXXX, KC_UP,   XXXXXXX, XXXXXXX, XXXXXXX, CK_LPRT, CK_RPRT, KC_MINS, KC_EQL,
    KC_TAB,  KC_LEFT, KC_DOWN, KC_RGHT, XXXXXXX, XXXXXXX, CK_LCBR, CK_RCBR, KC_QUOT, KC_BSLS,
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, KC_LBRC, KC_RBRC, KC_LGUI, XXXXXXX, XXXXXXX,
    XXXXXXX, XXXXXXX, XXXXXXX, KC_LSFT, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, MO(3)
  ),

  [3] = LAYOUT_default(
    RESET,   XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX
  ),

  [4] = LAYOUT_default(
    CK_CAPW, CK_CPYW,  CK_CAPP, CK_CPYP, CK_CPRC, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
    XXXXXXX, XXXXXXX,  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
    XXXXXXX, XXXXXXX,  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
    XXXXXXX, XXXXXXX,  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX
  ),

  [5] = LAYOUT_default(
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, KC_BTN1, KC_MS_U, KC_BTN2,
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, KC_MS_L, KC_MS_D, KC_MS_R, XXXXXXX,
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX
  ),

  [6] = LAYOUT_default(
    IJ_RFCTR, XXXXXXX, CK_LBMV,   CK_RBMV,   XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
    XXXXXXX,  XXXXXXX, CK_LAMV,   CK_RAMV,   XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
    XXXXXXX,  KC_ESC,  CK_LASLCT, CK_RASLCT, KC_TAB,  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
    XXXXXXX,  KC_LSFT, KC_LEFT,   KC_RGHT,   KC_BSPC, KC_DEL,  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX
  ),

  [7] = LAYOUT_default(
    KC_BRMD,     KC_BRMU,   KC_MPLY, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
    KC__VOLDOWN, KC__VOLUP, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
    KC_MRWD,     KC_MFFD,   XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
    XXXXXXX,     XXXXXXX,   XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX
  ),

  [8] = LAYOUT_default(
    XXXXXXX,  XXXXXXX,  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, CK_BGBS,
    CK_SWAPP, CK_SWWNW, CK_LTAB, CK_RTAB, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, CK_SMBS,
    XXXXXXX,  XXXXXXX,  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
    XXXXXXX,  XXXXXXX,  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX
  ),

  [9] = LAYOUT_default(
    XXXXXXX, KC_LEFT, XXXXXXX, KC_RGHT, XXXXXXX, XXXXXXX, CK_UNDO, CK_REDO, XXXXXXX, CK_BGBS,
    KC_LSFT, CK_LAMV, XXXXXXX, CK_RAMV, XXXXXXX, XXXXXXX, MO(10),  XXXXXXX, XXXXXXX, CK_SMBS,
    KC_LSFT, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX
  ),

  [10] = LAYOUT_default(
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
    XXXXXXX, CK_LBMV, XXXXXXX, CK_RBMV, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
    XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX
  ),
};
